function [puma, puma_CAD] = mdl_puma560(varargin)
%% Function: MDL_PUMA560
% Summary: Creates a model of the PUMA 560 Robotic Arm
%
% AUTHOR : ZACHARY LACEY
% AFFILIATION : UNIVERSITY OF CALIFORNIA, LOS ANGELES
% EMAIL : zlacey@g.ucla.edu
%         zlacey1234@gmail.com
%%
    clear L
    deg = pi/180;
    
    % Default DH Parameters
    
    a2 = 0.4318;
    d3 = 0.1254;
    
    a3 = 0.0191;
    d4 = 0.4318;
    
    % Transformation from the wrist to the tool 
    Px_6_tool = -0.10000;
    Pz_6_tool =  0.13625;

    T_wrist_tool = [1  0  0  Px_6_tool;...
                    0  1  0  0;...
                    0  0  1  Pz_6_tool;...
                    0  0  0  1];
    
    L = [
        RevoluteMDH('alpha', 0.0, ...
                    'a', 0.0, ...
                    'd', 0.0, ...
                    'qlim', [-160 160]*deg, ...
                    'm', 0.0, ...
                    'r', [0.0, 0.0, 0.0], ...
                    'I', [0.0, 0.0, 0.35, 0, 0, 0]);
                
        RevoluteMDH('alpha', -pi/2, ...
                    'a', 0.0, ...
                    'd', 0.0, ...
                    'qlim', [-223 43]*deg, ...   % 43
                    'm', 17.40, ...
                    'r', [0.068, 0.006, 0.2028], ...
                    'I', [0.13, 0.524, 0.539, 0, 0, 0]);
                    
        RevoluteMDH('alpha', 0.0, ...
                    'a', a2, ...
                    'd', d3, ...
                    'qlim', [-232 52]*deg, ...
                    'm', 4.80,...
                    'r', [0.0, 0.0687, 0.0140], ...
                    'I', [0.066, 0.0125, 0.066, 0, 0, 0]);
                    
        RevoluteMDH('alpha', -pi/2, ...
                    'a', a3, ...
                    'd', d4, ...
                    'qlim', [-140 140]*deg, ...
                    'm', 0.82);
                    
        RevoluteMDH('alpha', pi/2, ...
                    'a', 0.0, ...
                    'd', 0.0, ...
                    'qlim', [-100 100]*deg, ...
                    'm', 0.);
                                
        RevoluteMDH('alpha', -pi/2, ...
                    'a', 0.0, ...
                    'd', 0.0, ...
                    'qlim', [-266 266]*deg)
        ];
    
    puma = SerialLink(L, 'name', 'PUMA', 'tool', T_wrist_tool);
    puma_CAD = SerialLink(L, 'name', 'PUMA')
end